
server:
  port: 8082

spring:
  application:
    name: getway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  gateway:
        discovery:
          locator:
            enabled: true
        routes:
        # This route rule used to forward request to activity server
        - id: auth
          uri: lb://auth
          predicates:
          - Path=/auth/**
          filters:
          - StripPrefix=1

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8083/getAccount
      prefer-token-info: false
    authorization:
      check-token-access: http://localhost:8083/oauth/check_token

